name: CS

on:
  # Run on PRs and pushes, only on significant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  XMLLINT_INDENT: '	'

jobs:
    qa_checks:
        name: Quality control checks
        runs-on: ubuntu-latest

        steps:
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup PHP versions, run checks
            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                coverage: none
              env:
                COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set the required PHPCS and WPCS versions
              run: composer require squizlabs/php_codesniffer:"dev-master" wp-coding-standards/wpcs:"dev-master" --no-update --no-scripts

            # Install dependencies and handle caching in one go.
            # @link https://github.com/marketplace/actions/install-composer-dependencies
            - name: Install Composer dependencies
              uses: "ramsey/composer-install@v1"

            - name: Validate ruleset against schema
              uses: pipeline-components-xmllint@v0.1.0
              with:
                args: xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./*/ruleset.xml

            - name: Check the code-style consistency of the xml files.
              uses: pipeline-components-xmllint@v0.1.0
              with:
                args: diff -B --tabsize=4 ./WPThemeReview/ruleset.xml <(xmllint --format "./WPThemeReview/ruleset.xml")

            - name: Lint the PHP files against parse errors
              uses: pipeline-components-xmllint@v0.1.0
              with:
                args: if find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi

            - name: Validate the composer.json file.
              run: composer validate --no-check-all --strict

            - name: Check the code style of the WPThemeReview codebase
              run: composer check-cs

            - name: Check feature completeness of the available sniffs
              run: composer check-complete
