name: Test

on:
  # Run on pushes to `master` and on all pull requests.
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
    tests:
        name: PHP ${{ matrix.php }} with PHPCS ${{ matrix.phpcs_branch }}/WPCS ${{ matrix.wpcs_branch }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.allowed_failure }}
        strategy:
            fail-fast: false
            matrix:
                php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
                phpcs_branch: [ '3.5.0', 'dev-master' ]
                wpcs_branch: [ '2.3.0', 'dev-master' ]
                allowed_failure: [ false ]
                exclude:
                  - phpcs_branch: 'dev-master'
                    wpcs_branch: '2.3.0'
                  - phpcs_branch: '3.5.0'
                    wpcs_branch: 'dev-master'
                include:
                    - php: '7.2'
                      phpcs_branch: 'dev-master'
                      wpcs_branch: '2.3.0'
                      allowed_failure: false
                    - php: '7.2'
                      phpcs_branch: '3.5.0'
                      wpcs_branch: 'dev-develop'
                      allowed_failure: false
                    - php: '7.4'
                      phpcs_branch: 'dev-master'
                      wpcs_branch: 'dev-develop'
                      allowed_failure: true
                    - php: '8.0'
                      phpcs_branch: 'dev-master'
                      wpcs_branch: 'dev-master'
                      allowed_failure: true
                    - php: '8.0'
                      phpcs_branch: '3.5.0'
                      wpcs_branch: '2.3.0'
                      allowed_failure: true

        steps:
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup PHP versions, run checks
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                coverage: none
              env:
                COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set the minimum stability requirement for develop branch of WPCS
              env:
                PHPCS_BRANCH: ${{ matrix.phpcs_branch }}
                WPCS_BRANCH: ${{ matrix.wpcs_branch }}
              if: ${{ matrix.wpcs_branch == 'dev-develop' }}
              run: |
                composer config minimum-stability dev
                composer require squizlabs/php_codesniffer:${PHPCS_BRANCH} wp-coding-standards/wpcs:${WPCS_BRANCH} --no-update --no-scripts

            - name: Set the required PHPCS and WPCS versions
              env:
                PHPCS_BRANCH: ${{ matrix.phpcs_branch }}
                WPCS_BRANCH: ${{ matrix.wpcs_branch }}
              run: composer require squizlabs/php_codesniffer:${PHPCS_BRANCH} wp-coding-standards/wpcs:${WPCS_BRANCH} --no-update --no-scripts

            # Install dependencies and handle caching in one go.
            # @link https://github.com/marketplace/actions/install-composer-dependencies
            - name: Install Composer dependencies
              uses: "ramsey/composer-install@v1"

            - name: Run tests
              run: composer run-tests
